# Step 11 — Answer the six business questions

This notebook runs the same six SQL business questions against the completed ETL and ELT September warehouses. Each query is stored in a checked-in SQL file, and every result is displayed and exported for submission.

The notebook uses read-only warehouse connections and does not edit source data or the read-only snapshots.

In [1]:
# Import the SQL runner and configure paths to the Step 9 warehouse artifacts.
from pathlib import Path
import sys

REPO_ROOT = Path.cwd()
if not (REPO_ROOT / 'include').exists():
    REPO_ROOT = Path.cwd().parent
sys.path.insert(0, str(REPO_ROOT / 'include'))

from business_questions import (
    explain_september_difference,
    run_business_questions,
    september_revenue,
)

ETL_DB = REPO_ROOT / 'assignment' / 'warehouse_samy_etl_step9.duckdb'
ELT_DB = REPO_ROOT / 'assignment' / 'warehouse_samy_elt_step9.duckdb'
assert ETL_DB.exists(), f'Missing ETL warehouse: {ETL_DB}'
assert ELT_DB.exists(), f'Missing ELT warehouse: {ELT_DB}'
print(f'ETL warehouse: {ETL_DB}')
print(f'ELT warehouse: {ELT_DB}')

ETL warehouse: /Users/kumarsamanvaya/Documents/IITR - FDE Course/Data Pipepline Assignment/_Samy_IIT_Roorkie_CEC_Futurenece_Data_Pipeline_to_ML_Model/assignment/warehouse_samy_etl_step9.duckdb
ELT warehouse: /Users/kumarsamanvaya/Documents/IITR - FDE Course/Data Pipepline Assignment/_Samy_IIT_Roorkie_CEC_Futurenece_Data_Pipeline_to_ML_Model/assignment/warehouse_samy_elt_step9.duckdb

In [2]:
# Execute all six queries for each pipeline. The SQL files contain one
# named query per business question, so results remain easy to audit.
etl_results = run_business_questions(ETL_DB, 'ETL')
elt_results = run_business_questions(ELT_DB, 'ELT')

for question_name in etl_results:
    print(f'\n=== {question_name} — ETL ===')
    display(etl_results[question_name])
    print(f'=== {question_name} — ELT ===')
    display(elt_results[question_name])

=== q1_daily_revenue_by_zone_store — ETL ===

     order_date   zone store_id  daily_net_revenue  delivered_orders
0    2026-09-01   East      S08            2984.70                 4
1    2026-09-01   East      S09            2089.60                 4
2    2026-09-01   East      S10            2141.60                 3
3    2026-09-01   East      S11            2121.15                 6
4    2026-09-01  North      S01            1410.80                 3
..          ...    ...      ...                ...               ...
379  2026-09-30  South      S05            3823.35                 6
380  2026-09-30  South      S06            2493.50                 5
381  2026-09-30   West      S13            1301.60                 5
382  2026-09-30   West      S14            1760.45                 3
383  2026-09-30   West      S15             357.00                 1

[384 rows x 5 columns]

=== q1_daily_revenue_by_zone_store — ELT ===

    order_date   zone store_id  daily_net_revenue  delivered_orders
0   2026-09-01   East      S08            2984.70                 4
1   2026-09-01   East      S09            2089.60                 4
2   2026-09-01   East      S10            2141.60                 3
3   2026-09-01   East      S11            2121.15                 6
4   2026-09-01  North      S01            1410.80                 3
..         ...    ...      ...                ...               ...
379 2026-09-30  South      S05            3823.35                 6
380 2026-09-30  South      S06            2493.50                 5
381 2026-09-30   West      S13            1301.60                 5
382 2026-09-30   West      S14            1760.45                 3
383 2026-09-30   West      S15             357.00                 1

[384 rows x 5 columns]

=== q2_revenue_margin_by_category — ETL ===

              category    revenue  gross_margin
0              Staples  212686.00      54563.95
1        Personal Care  179965.60      39824.12
2            Household  166866.55      42326.26
3       Dairy & Bakery  149028.75      39177.96
4   Snacks & Beverages  148381.10      33965.22
5  Fruits & Vegetables   75956.15      18226.14

=== q2_revenue_margin_by_category — ELT ===

              category    revenue  gross_margin
0              Staples  212686.00      54563.95
1        Personal Care  179965.60      39824.12
2            Household  166866.55      42326.26
3       Dairy & Bakery  149028.75      39177.96
4   Snacks & Beverages  148381.10      33965.22
5  Fruits & Vegetables   75956.15      18226.14

=== q3_delivery_sla — ETL ===

   store_id  average_delivery_minutes  pct_within_15_min  delivered_orders
0       S01                 20.875969          29.457364               129
1       S02                 21.261538          28.461538               130
2       S03                 20.721805          30.075188               133
3       S04                 21.774194          25.806452               124
4       S05                 21.520325          29.268293               123
5       S06                 22.380282          22.535211               142
6       S08                 20.531469          36.363636               143
7       S09                 21.303279          27.868852               122
8       S10                 21.838462          27.692308               130
9       S11                 21.255814          27.906977               129
10      S13                 21.716535          27.559055               127
11      S14                 21.893333          30.666667               150
12      S15                 22.560284          20.567376               141

=== q3_delivery_sla — ELT ===

   store_id  average_delivery_minutes  pct_within_15_min  delivered_orders
0       S01                 20.875969          29.457364               129
1       S02                 21.261538          28.461538               130
2       S03                 20.721805          30.075188               133
3       S04                 21.774194          25.806452               124
4       S05                 21.520325          29.268293               123
5       S06                 22.380282          22.535211               142
6       S08                 20.531469          36.363636               143
7       S09                 21.303279          27.868852               122
8       S10                 21.838462          27.692308               130
9       S11                 21.255814          27.906977               129
10      S13                 21.716535          27.559055               127
11      S14                 21.893333          30.666667               150
12      S15                 22.560284          20.567376               141

=== q4_payment_mode_reconciliation — ETL ===

       payment_mode    revenue  unreconciled_amount  unreconciled_rows
0              Card  187847.00             28130.15                139
1  Cash on Delivery  124881.40             51308.50                 94
2               UPI  518439.75             96318.80                341
3            Wallet  101716.00             22112.50                 55

=== q4_payment_mode_reconciliation — ELT ===

       payment_mode    revenue  unreconciled_amount  unreconciled_rows
0              Card  187847.00             28130.15                139
1  Cash on Delivery  124881.40             51308.50                 94
2               UPI  518439.75             96318.80                341
3            Wallet  101716.00             22112.50                 55

=== q5_top_customers — ETL ===

  customer_id       full_name loyalty_tier  total_spend
0      C00310     Kiran Patil       Bronze      7258.95
1      C00072  Nandini Murthy       Silver      6433.95
2      C00283      Nikhil Rao       Bronze      6241.40
3      C00236     Sneha Naidu     Platinum      6105.80
4      C00202      Priya Bhat       Silver      5988.75
5      C00328      Ritu Hegde       Bronze      5877.90
6      C00036     Deepa Desai       Bronze      5835.70
7      C00115    Sanjay Kumar       Bronze      5783.70
8      C00105    Mahesh Gowda         Gold      5702.85
9      C00135     Deepa Desai       Bronze      5693.20

=== q5_top_customers — ELT ===

  customer_id       full_name loyalty_tier  total_spend
0      C00310     Kiran Patil       Bronze      7258.95
1      C00072  Nandini Murthy       Silver      6433.95
2      C00283      Nikhil Rao       Bronze      6241.40
3      C00236     Sneha Naidu     Platinum      6105.80
4      C00202      Priya Bhat       Silver      5988.75
5      C00328      Ritu Hegde       Bronze      5877.90
6      C00036     Deepa Desai       Bronze      5835.70
7      C00115    Sanjay Kumar       Bronze      5783.70
8      C00105    Mahesh Gowda         Gold      5702.85
9      C00135     Deepa Desai       Bronze      5693.20

=== q6_rejected_rows — ETL ===

,file_name,failure_reason,severity,rejected_rows
0,customers.csv,Invalid email format,Warning,12
1,customers.csv,Duplicate customer_id,Critical,10
2,customers.csv,Loyalty tier casing is not standard,Warning,8
3,customers.csv,Phone is not a 10-digit number,Warning,7
4,customers.csv,Pincode is not six digits,Warning,3
5,customers.csv,Future signup_date,Warning,3
6,orders.csv,Duplicate order_id,Critical,24
7,orders.csv,Amount does not match pricing formula,Critical,18
8,orders.csv,Unknown customer_id,Critical,18
9,orders.csv,Missing customer_id,Critical,18
10,orders.csv,Quantity is not positive,Critical,10
11,orders.csv,Unknown product_id,Critical,9
12,orders.csv,Delivered order has no delivery time,Critical,8
13,orders.csv,Future-dated order,Critical,7
14,orders.csv,Delivery time exceeds 120 minutes,Critical,6
15,orders.csv,order_ts is not a valid timestamp,Critical,6
16,orders.csv,Unknown store_id,Critical,5
17,orders.csv,Invalid order status,Critical,3
18,orders.csv,Discount outside 0-100,Critical,3
19,orders.csv,Latest order older than 1 day,Warning,1
20,payments.csv,Missing gateway reference,Warning,301
21,payments.csv,Successful payment does not equal order amount,Critical,14
22,payments.csv,Payment amount is not positive,Critical,10
23,payments.csv,Unknown order_id,Critical,8
24,payments.csv,Duplicate payment_id,Critical,8
25,products.csv,Cost price exceeds MRP,Critical,5
26,products.csv,Duplicate product_id,Critical,4
27,products.csv,Missing category,Critical,3
28,products.csv,MRP is not positive,Critical,1
29,stores.csv,Missing zone,Critical,1
30,stores.csv,Store capacity is not positive,Critical,1

=== q6_rejected_rows — ELT ===

,file_name,failure_reason,severity,rejected_rows
0,customers.csv,Invalid email format,Warning,12
1,customers.csv,Duplicate customer_id,Critical,10
2,customers.csv,Loyalty tier casing is not standard,Warning,8
3,customers.csv,Phone is not a 10-digit number,Warning,7
4,customers.csv,Pincode is not six digits,Warning,3
5,customers.csv,Future signup_date,Warning,3
6,orders.csv,Duplicate order_id,Critical,24
7,orders.csv,Amount does not match pricing formula,Critical,18
8,orders.csv,Unknown customer_id,Critical,18
9,orders.csv,Missing customer_id,Critical,18
10,orders.csv,Quantity is not positive,Critical,10
11,orders.csv,Unknown product_id,Critical,9
12,orders.csv,Delivered order has no delivery time,Critical,8
13,orders.csv,Future-dated order,Critical,7
14,orders.csv,Delivery time exceeds 120 minutes,Critical,6
15,orders.csv,order_ts is not a valid timestamp,Critical,6
16,orders.csv,Unknown store_id,Critical,5
17,orders.csv,Invalid order status,Critical,3
18,orders.csv,Discount outside 0-100,Critical,3
19,orders.csv,Latest order older than 1 day,Warning,1
20,payments.csv,Missing gateway reference,Warning,301
21,payments.csv,Successful payment does not equal order amount,Critical,14
22,payments.csv,Payment amount is not positive,Critical,10
23,payments.csv,Unknown order_id,Critical,8
24,payments.csv,Duplicate payment_id,Critical,8
25,products.csv,Cost price exceeds MRP,Critical,5
26,products.csv,Duplicate product_id,Critical,4
27,products.csv,Missing category,Critical,3
28,products.csv,MRP is not positive,Critical,1
29,stores.csv,Missing zone,Critical,1
30,stores.csv,Store capacity is not positive,Critical,1

In [3]:
# Compare the like-for-like September delivered net-revenue totals.
# If they differ, list the exact order IDs included by only one pipeline.
etl_total = september_revenue(ETL_DB, 'ETL')
elt_total = september_revenue(ELT_DB, 'ELT')
difference = etl_total - elt_total
print(f'ETL September net revenue: {etl_total:,.2f}')
print(f'ELT September net revenue: {elt_total:,.2f}')
print(f'Difference (ETL - ELT): {difference:,.2f}')

if abs(difference) < 0.01:
    print('September totals match within one cent.')
else:
    differences = explain_september_difference(ETL_DB, ELT_DB)
    print('Totals differ. The following order IDs explain the difference:')
    display(differences)
    print('Interpretation: ETL excludes rows failing critical Python checks before the fact table; ELT applies its SQL staging rules and therefore may retain a different set of passing rows.')

ETL September net revenue: 932,884.15
ELT September net revenue: 932,884.15
Difference (ETL - ELT): -0.00
September totals match within one cent.

In [4]:
# Export every result so the SQL answers can be attached to the submission.
output_dir = REPO_ROOT / 'assignment' / 'step11_business_questions'
output_dir.mkdir(parents=True, exist_ok=True)
for pipeline_name, results in [('etl', etl_results), ('elt', elt_results)]:
    for question_name, frame in results.items():
        frame.to_csv(output_dir / f'{pipeline_name}_{question_name}.csv', index=False)

comparison = {
    'etl_september_net_revenue': etl_total,
    'elt_september_net_revenue': elt_total,
    'difference_etl_minus_elt': difference,
}
import json
(output_dir / 'september_total_comparison.json').write_text(json.dumps(comparison, indent=2))
print(f'Exported {len(etl_results) + len(elt_results)} result CSV files to {output_dir}')
print('Exported September total comparison to september_total_comparison.json')

Exported 12 result CSV files to /Users/kumarsamanvaya/Documents/IITR - FDE Course/Data Pipepline Assignment/_Samy_IIT_Roorkie_CEC_Futurenece_Data_Pipeline_to_ML_Model/assignment/step11_business_questions
Exported September total comparison to september_total_comparison.json

## Business-question mapping

1. Daily net revenue by zone and store → `etl_daily_zone_revenue` / `mart_daily_store_kpis`.
2. Revenue and gross margin by category → `etl_category_margin` / `mart_category_margin`.
3. Average delivery time and percentage within 15 minutes → ETL fact calculation / `mart_delivery_sla`.
4. Revenue by payment mode and unreconciled amount → ETL fact plus reconciliation / staging plus `mart_payment_reconciliation`.
5. Top 10 customers by spend and loyalty tier → ETL dimensions plus fact / `mart_top_customers`.
6. Rejected rows by file and failure reason → ETL `dq_results` / ELT staging `dq_status` and `failure_reason`.