# Step 4 — Reusable data-quality helpers

This notebook tests the shared validation and PII-masking helpers before they are called from Airflow. The source CSV files are read only; no input file is changed.

Flow: load data → run six quality dimensions → inspect `dq_results` → inspect quarantine candidates → test masking → save local outputs.

In [1]:
from pathlib import Path
import sys
import pandas as pd

# Add the repository's include directory so the notebook uses the same helpers as Airflow.
INCLUDE_DIR = Path('include')
sys.path.insert(0, str(INCLUDE_DIR.resolve()))

from data_quality import run_quality_checks
from masking import mask_email, mask_phone

DATA_DIR = Path('include/data/nammamart')
FILES = {
    'orders': 'orders.csv',
    'orders_increment': 'orders_2026-10-01_increment.csv',
    'payments': 'payments.csv',
    'customers': 'customers.csv',
    'products': 'products.csv',
    'stores': 'stores.csv',
}

# Keeping the file-to-DataFrame mapping explicit makes the later DAG calls easy to follow.
data = {name: pd.read_csv(DATA_DIR / filename) for name, filename in FILES.items()}
for name, frame in data.items():
    print(f'{name:18} {len(frame):5,} rows loaded')

orders             2,412 rows loaded
orders_increment     160 rows loaded
payments           2,228 rows loaded
customers            405 rows loaded
products             152 rows loaded
stores                15 rows loaded

In [2]:
# Run all shared validation rules with the same identifiers that will be stored in DuckDB.
issues, dq_results = run_quality_checks(
    data,
    run_id='step4-local-test',
    dag_id='nammamart_quality_helpers_test',
)

print(f'Issue instances: {len(issues):,}')
print(f'Quality checks: {len(dq_results):,}')
print(f'Failed checks: {(dq_results["status"] == "FAIL").sum():,}')
display(dq_results[['check_name', 'dimension', 'severity', 'rows_checked', 'rows_failed', 'status']])

Issue instances: 534
Quality checks: 36
Failed checks: 31

,check_name,dimension,severity,rows_checked,rows_failed,status
0,orders.csv:customer_id:Missing customer_id,Completeness,Critical,2412,18,FAIL
1,orders.csv:order_id:Duplicate order_id,Uniqueness,Critical,2412,24,FAIL
2,orders.csv:order_status:Invalid order status,Validity,Critical,2412,3,FAIL
3,orders.csv:payment_mode:Invalid payment mode,Validity,Critical,2412,0,PASS
4,orders.csv:quantity:Quantity is not positive,Accuracy,Critical,2412,10,FAIL
5,orders.csv:order_amount:Amount does not match ...,Accuracy,Critical,2412,18,FAIL
6,orders.csv:delivery_minutes:Delivered order ha...,Completeness,Critical,2412,8,FAIL
7,orders.csv:delivery_minutes:Delivery time exce...,Accuracy,Critical,2412,6,FAIL
8,orders.csv:discount_pct:Discount outside 0-100,Validity,Critical,2412,3,FAIL
9,orders.csv:order_ts:order_ts is not a valid ti...,Validity,Critical,2412,6,FAIL
10,orders.csv:order_ts:Future-dated order,Timeliness,Critical,2412,7,FAIL
11,orders.csv:customer_id:Unknown customer_id,Consistency,Critical,2412,18,FAIL
12,orders.csv:product_id:Unknown product_id,Consistency,Critical,2412,9,FAIL
13,orders.csv:store_id:Unknown store_id,Consistency,Critical,2412,5,FAIL
14,orders.csv:order_ts:Latest order older than 1 day,Timeliness,Warning,2412,1,FAIL
15,payments.csv:payment_id:Duplicate payment_id,Uniqueness,Critical,2228,8,FAIL
16,payments.csv:gateway_ref:Missing gateway refer...,Completeness,Warning,2228,301,FAIL
17,payments.csv:amount_paid:Payment amount is not...,Accuracy,Critical,2228,10,FAIL
18,payments.csv:order_id:Unknown order_id,Consistency,Critical,2228,8,FAIL
19,payments.csv:amount_paid:Successful payment do...,Consistency,Critical,2240,14,FAIL
20,customers.csv:customer_id:Duplicate customer_id,Uniqueness,Critical,405,10,FAIL
21,customers.csv:email:Invalid email format,Validity,Warning,405,12,FAIL
22,customers.csv:phone:Phone is not a 10-digit nu...,Validity,Warning,405,7,FAIL
23,customers.csv:loyalty_tier:Loyalty tier casing...,Consistency,Warning,405,8,FAIL
24,customers.csv:signup_date:Future signup_date,Timeliness,Warning,405,3,FAIL
25,customers.csv:pincode:Pincode is not six digits,Validity,Warning,405,3,FAIL
26,products.csv:product_id:Duplicate product_id,Uniqueness,Critical,152,4,FAIL
27,products.csv:category:Missing category,Completeness,Critical,152,3,FAIL
28,products.csv:mrp:MRP is not positive,Accuracy,Critical,152,1,FAIL
29,products.csv:cost_price:Cost price exceeds MRP,Accuracy,Critical,152,5,FAIL
30,stores.csv:store_id:Duplicate store_id,Uniqueness,Critical,15,0,PASS
31,stores.csv:zone:Missing zone,Completeness,Critical,15,1,FAIL
32,stores.csv:pincode:Pincode is not six digits,Validity,Warning,15,0,PASS
33,stores.csv:capacity_orders_per_day:Store capac...,Accuracy,Critical,15,1,FAIL
34,orders_2026-10-01_increment.csv:order_amount:A...,Accuracy,Critical,160,0,PASS
35,orders_2026-10-01_increment.csv:order_status:I...,Validity,Critical,160,0,PASS

In [3]:
# Summarise failures by file, dimension and severity so the ETL DAG can route them.
display(issues.groupby(['file', 'quality_dimension', 'severity']).size().rename('issue_rows').reset_index())

# Critical rows are quarantine candidates; warnings remain loadable but are logged.
quarantine_candidates = issues[issues['severity'] == 'Critical']
warning_rows = issues[issues['severity'] == 'Warning']
print(f'Critical quarantine candidates: {len(quarantine_candidates):,}')
print(f'Warning rows to log: {len(warning_rows):,}')
display(issues.head(20))

             file quality_dimension  severity  issue_rows
0   customers.csv       Consistency   Warning           8
1   customers.csv        Timeliness   Warning           3
2   customers.csv        Uniqueness  Critical          10
3   customers.csv          Validity   Warning          22
4      orders.csv          Accuracy  Critical          34
5      orders.csv      Completeness  Critical          26
6      orders.csv       Consistency  Critical          32
7      orders.csv        Timeliness  Critical           7
8      orders.csv        Uniqueness  Critical          24
9      orders.csv          Validity  Critical          12
10   payments.csv          Accuracy  Critical          10
11   payments.csv      Completeness   Warning         301
12   payments.csv       Consistency  Critical          22
13   payments.csv        Uniqueness  Critical           8
14   products.csv          Accuracy  Critical           6
15   products.csv      Completeness  Critical           3
16   products.csv        Uniqueness  Critical           4
17     stores.csv          Accuracy  Critical           1
18     stores.csv      Completeness  Critical           1

Critical quarantine candidates: 200
Warning rows to log: 334

,file,row_key,column,problem,quality_dimension,proposed_rule,severity
0,orders.csv,ORD002255,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
1,orders.csv,ORD000701,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
2,orders.csv,ORD000997,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
3,orders.csv,ORD000580,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
4,orders.csv,ORD002019,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
5,orders.csv,ORD002262,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
6,orders.csv,ORD002149,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
7,orders.csv,ORD002367,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
8,orders.csv,ORD001332,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
9,orders.csv,ORD001918,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
10,orders.csv,ORD002156,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
11,orders.csv,ORD000583,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
12,orders.csv,ORD000790,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
13,orders.csv,ORD000764,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
14,orders.csv,ORD002219,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
15,orders.csv,ORD001532,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
16,orders.csv,ORD000022,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
17,orders.csv,ORD001373,customer_id,Missing customer_id,Completeness,customer_id must be present,Critical
18,orders.csv,ORD001462,order_id,Duplicate order_id,Uniqueness,order_id must be unique,Critical
19,orders.csv,ORD001326,order_id,Duplicate order_id,Uniqueness,order_id must be unique,Critical

In [4]:
# Verify that personal data is masked before it can enter reporting tables.
mask_examples = pd.DataFrame({
    'original_email': ['priya.hegde199@example.com', 'invalid-email'],
    'masked_email': [mask_email('priya.hegde199@example.com'), mask_email('invalid-email')],
    'original_phone': ['9774349021', '123'],
    'masked_phone': [mask_phone('9774349021'), mask_phone('123')],
})
display(mask_examples)

# These files mirror the future dq_results and quarantine inputs to the pipeline.
Path('assignment').mkdir(exist_ok=True)
issues.to_csv('assignment/data_issues_log_step4.csv', index=False)
dq_results.to_csv('assignment/dq_results_step4.csv', index=False)
print('Wrote assignment/data_issues_log_step4.csv')
print('Wrote assignment/dq_results_step4.csv')

               original_email       masked_email original_phone masked_phone
0  priya.hegde199@example.com  pr***@example.com     9774349021   97******21
1               invalid-email                ***            123          ***

Wrote assignment/data_issues_log_step4.csv
Wrote assignment/dq_results_step4.csv